### ISSUE TITLE
Job on top is the only one that runs

### ISSUE THREAD

**Issue by RoyVandenBroeck** [VeeamHub/vbo365-rest-self-service#11]
Hi,

I stumbled upon an issue when trying to run a backup job from the portal.
I currently have multiple jobs set up, and only the topmost job is able to be turned on/off and can start the backup job.
All the other jobs below the top most job won't turn on/off or won't start.
When I remove the top most job from the Veeam Backup, the newest topmost job in the portal is able to perform the actions, but the ones below still won't.
There is no issue viewing the schedules and restore points that have been made.

It is also not possible to view schedules and restore points when using the search/filter bar, searching for a specific job and then looking at one of those.

And lastly a refresh of the page is required between turning a job on and off.
example1: I can turn a job off but cannot turn it on again without a page refresh.
example2: I can turn a job off, start that job, but not turn it on again without a page refresh.

Thanks in advance

**Comment by nielsengelen** [comment]
Hi Roy,

I just did a test and could start multiple jobs one by one. Also, when u disable or enable a job, the icon should change. Are you saying this doesn't happen for you? Can u check if u block specific javascript calls on the page?

**Comment by RoyVandenBroeck** [comment]
Hi,

The top row of the jobs works when pressing the buttons. The buttons on the row below are non responsive. There is no java-script call that is being blocked, but there is also no java-script call being made when I press a button that is not on the top row

**Comment by nielsengelen** [comment]
I've managed to reproduce the button issue and will look into creating a fix for it. 

The 'issue' when you start a job and the need for a page refresh is actually by design and I will see if I can improve this as well but I can't provide a direct ETA on this.

**Comment by nielsengelen** [comment]
I've updated [the jobs.php file ](https://github.com/VeeamHub/vbo365-rest-self-service/blob/1da42cd02cf6b8823abf7aec4c943bb772fded86/includes/jobs.php). This should resolve the button issue. I've also removed the extra popup saying the state change. Could you test it out and let me know if it solves the issue? You can just download the raw file and replace it. No need to git clone. 

The state change when u start a job will be for the next update as it requires some more changes.

**Comment by RoyVandenBroeck** [comment]
I no longer get the popup as you've mentioned but the issue still persists, only the top row of buttons is responsive.
The other rows still won't make any calls.

**Comment by nielsengelen** [comment]
I've changed the behavior and linking of the buttons which seems to work better now as the previous change also broke "start job" button. It has been tested in an environment with 25 jobs by randomly enabling/disabling and starting jobs. I've once again updated [the jobs.php file ](https://github.com/VeeamHub/vbo365-rest-self-service/blob/1da42cd02cf6b8823abf7aec4c943bb772fded86/includes/jobs.php). 

Can you try the update and see if it works well now?

**Comment by RoyVandenBroeck** [comment]
The other buttons seem to be working now, thank you very much

**Comment by nielsengelen** [comment]
Great, thanks for the update.
